--INSERTS usuarios
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('1', 'Charles', 'Queensworth', 'cqueensworth@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('2', 'Kiyori', 'Nattoro', 'knattoro@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('3', 'Daub', 'Swanna', 'dswanna@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('4', 'Juan', 'Garcia Orondo', 'jgorondo@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('5', 'Alejandra', 'Rubio Herrero', 'arherrero@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('6', 'John', 'Carter', 'jcarter@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('7', 'Usher', 'Aussie', 'uassie@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('8', 'Liam', 'Washington', 'lwashington@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('9', 'Olivia', 'Autumn', 'oautumn@gmail.no', 'qwerty');
INSERT INTO USERS (id_user, user_name, user_surname, email, user_password) VALUES ('10', 'Anna', 'Barikovich', 'abarikovich@gmail.no', 'qwerty');

--INSERTS autores
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('1', 'Maya', 'Angelou', '04/04/1928', 'Poet, author, and civil rights activist Maya Angelou was a champion for black feminism and is best remembered for her autobiography, I Know Why the Caged Bird Sing. The recipient of the Presidential Medal of Freedom and over 50 honorary degrees was also a child sex abuse survivor.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('2', 'Noam', 'Chomsky', '07/12/1928', 'Regarded by many as the father of modern linguistics, Noam Chomsky has authored over 100 books on varied topics, such as politics, linguistics, and war. A multi-talented personality, Noam Chomsky is considered a popular figure in analytic philosophy. Apart from influencing a wide array of academic fields, he has also contributed to the development of cognitivism.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('3', 'Kurt', 'Vonnegut', '11/11/1922', 'Science-fiction author Kurt Vonnegut is best remembered for the novel Slaughterhouse-Five, which became a New York Times bestseller. The Hugo Award-winner had also fought against the Germans in World War II and expressed his anti-war and atheist views through his works, which also include short stories, plays, and autobiographical works.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('4', 'Margaret', 'Atwood', '18/11/1939', 'Margaret Atwood is a Canadian poet and novelist. Her works encompass themes, such as religion and myth, climate change, and gender and identity. An award-winning writer, many of Atwood"s works have been made into films and television series; her work, The Handmaid"s Tale, has had several adaptations.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('5', 'David', 'Foster Wallace', '21/02/1962', 'David Foster Wallace was an American author who is regarded as one of the most innovative and influential writers of the past 20 years. His best-known work, Infinite Jest, was named one of the best English-language novels between 1923 and 2005 by Time magazine.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('6', 'Richard', 'Dawkins', '26/03/1941', 'Richard Dawkins is a British ethologist, author, and evolutionary biologist. He first achieved popularity after publishing his book, The Selfish Gene, which is credited with popularizing the gene selection theory.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('7', 'George', 'R. R. Martin', '20/09/1948', 'George R. R. Martin wrote the epic fantasy series of novels, A Song of Ice and Fire, which inspired the iconic Emmy-winning HBO series Game of Thrones. Also known as the "American Tolkien," he was featured on TIME 100. He has earned the Hugo, Nebula, and Bram Stoker awards, too.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('8', 'Umberto', 'Eco', '05/01/1932', 'Italian novelist Umberto Eco is best remembered for his novels The Name of the Rose and Foucault"s Pendulum. He also taught at the University of Bologna and had released quite a few children"s books and translations. He was also known for his work on semiotics and medieval studies.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('9', 'Isabel', 'Allende', '02/08/1942', 'Chilean author Isabel Allende is known for her bestselling Spanish-language novels The House of the Spirits and City of the Beasts. The Chilean National Literature Prize-winner explores women’s perspectives and includes magic realism and autobiographical aspects in her works.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('10', 'Carlos', 'Ruiz Zafon', '25/09/1964', 'Su obra más famosa es La sombra del viento, con 15 millones de ejemplares vendidos y ganadora de numerosos galardones fue seleccionada en la lista confeccionada en 2007 por ochenta y un escritores y críticos latinoamericanos y españoles entre los cien mejores libros en lengua española de los últimos veinticinco años.');
INSERT INTO AUTHORS (id_author, author_name, author_surname, author_birthdate, author_description) VALUES ('11', 'Almudena', 'Grandes', '07/05/1960', 'Galardonada con el Premio Nacional de Narrativa en 2018, la mayor parte de su obra trata de ahondar en la historia reciente de España para recuperar las huellas de un pasado oculto durante la dictadura de Francisco Franco y explicar las claves de la sociedad española de finales del siglo XX y primeras décadas del siglo XXI.');

--INSERTS libros
INSERT INTO BOOKS (id_book, title, publish_date, page_num, book_description) VALUES ();
