-- DROP tablas
DROP TABLE USERS;
DROP TABLE AUTHORS;
DROP TABLE BOOKS;
DROP TABLE REVIEWS;

-- CREATE tablas: USERS, AUTHORS, BOOKS, REVIEWS
CREATE TABLE USERS(
id_user INT,
user_name VARCHAR2(20),
user_surname VARCHAR2(30),
email VARCHAR2(25),
user_password VARCHAR2(30),
CONSTRAINT PK_ID_USER PRIMARY KEY(id_user)
);

CREATE TABLE AUTHORS(
id_author INT,
author_name VARCHAR2(20),
author_surname VARCHAR2(30),
author_birthdate DATE,
author_description VARCHAR2(200),
CONSTRAINT PK_ID_USER PRIMARY KEY(id_user)
);


CREATE TABLE BOOKS(
id_book INT,
title VARCHAR2(30),
publish_date DATE,
page_num INT,
book_description VARCHAR2(200),
CONSTRAINT PK_ID_BOOK PRIMARY KEY(id_book),
CONSTRAINT FK_ID_AUTHOR_BOOK FOREIGN KEY(id_author) REFERENCES AUTHORS
);

CREATE TABLE REVIEWS(
id_review INT,
review_content VARCHAR2(100),
review_rating CHAR(1),
CONSTRAINT PK_ID_REVIEW PRIMARY KEY(id_review),
CONSTRAINT FK_ID_BOOK_REVIEW FOREIGN KEY(id_book) REFERENCES BOOKS,
CONSTRAINT FK_ID_USER_REVIEW FOREIGN KEY(id_user) REFERENCES USERS
);